# Generated by Django 4.1 on 2022-08-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCampus',
            fields=[
                ('campus_name', models.CharField(blank=True, default='', max_length=60)),
                ('campus_state', models.CharField(blank=True, default='', max_length=2)),
                ('campus_id', models.IntegerField(blank=True, default='', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'University Campus',
            },
        ),
    ]
